language: csharp
solution: TheObserverPattern.sln
install:
  - nuget restore TheObserverPattern.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug TheObserverPattern.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./ObserverPattern_Tests/bin/Debug/ObserverPattern_Tests.dll